// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unused_field
// ignore_for_file: unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for librelay.h (Go SFU Core).
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FlutterSfuRelayBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterSfuRelayBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterSfuRelayBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int _GoStringLen(_GoString_ s) {
    return __GoStringLen(s);
  }

  late final __GoStringLenPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(_GoString_)>>(
        '_GoStringLen',
      );
  late final __GoStringLen = __GoStringLenPtr
      .asFunction<int Function(_GoString_)>();

  ffi.Pointer<ffi.Char> _GoStringPtr(_GoString_ s) {
    return __GoStringPtr(s);
  }

  late final __GoStringPtrPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(_GoString_)>>(
        '_GoStringPtr',
      );
  late final __GoStringPtr = __GoStringPtrPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(_GoString_)>();

  /// Mutex for thread-safe ping callback access
  late final ffi.Pointer<pthread_mutex_t> _pingCallbackMutex =
      _lookup<pthread_mutex_t>('pingCallbackMutex');

  pthread_mutex_t get pingCallbackMutex => _pingCallbackMutex.ref;

  /// 存储 ping 回调
  late final ffi.Pointer<PingCallback> _pingCallback = _lookup<PingCallback>(
    'pingCallback',
  );

  PingCallback get pingCallback => _pingCallback.value;

  set pingCallback(PingCallback value) => _pingCallback.value = value;

  void setPingCallback(PingCallback cb) {
    return _setPingCallback(cb);
  }

  late final _setPingCallbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(PingCallback)>>(
        'setPingCallback',
      );
  late final _setPingCallback = _setPingCallbackPtr
      .asFunction<void Function(PingCallback)>();

  void invalidatePingCallback() {
    return _invalidatePingCallback();
  }

  late final _invalidatePingCallbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
        'invalidatePingCallback',
      );
  late final _invalidatePingCallback = _invalidatePingCallbackPtr
      .asFunction<void Function()>();

  void callPingCallback(ffi.Pointer<ffi.Char> peerID) {
    return _callPingCallback(peerID);
  }

  late final _callPingCallbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'callPingCallback',
      );
  late final _callPingCallback = _callPingCallbackPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Generation counter for detecting stale callbacks
  /// Incremented each time callbacks are set or cleared
  late final ffi.Pointer<ffi.Int64> _callbackGeneration = _lookup<ffi.Int64>(
    'callbackGeneration',
  );

  int get callbackGeneration => _callbackGeneration.value;

  set callbackGeneration(int value) => _callbackGeneration.value = value;

  /// Mutex for thread-safe callback access
  late final ffi.Pointer<pthread_mutex_t> _callbackMutex =
      _lookup<pthread_mutex_t>('callbackMutex');

  pthread_mutex_t get callbackMutex => _callbackMutex.ref;

  /// Store the callbacks
  late final ffi.Pointer<EventCallback> _eventCallback = _lookup<EventCallback>(
    'eventCallback',
  );

  EventCallback get eventCallback => _eventCallback.value;

  set eventCallback(EventCallback value) => _eventCallback.value = value;

  late final ffi.Pointer<LogCallback> _logCallback = _lookup<LogCallback>(
    'logCallback',
  );

  LogCallback get logCallback => _logCallback.value;

  set logCallback(LogCallback value) => _logCallback.value = value;

  /// Get current generation (for Go code to check before/after)
  int getCallbackGeneration() {
    return _getCallbackGeneration();
  }

  late final _getCallbackGenerationPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'getCallbackGeneration',
      );
  late final _getCallbackGeneration = _getCallbackGenerationPtr
      .asFunction<int Function()>();

  /// Setter functions - increment generation on each change
  void setEventCallback(EventCallback cb) {
    return _setEventCallback(cb);
  }

  late final _setEventCallbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(EventCallback)>>(
        'setEventCallback',
      );
  late final _setEventCallback = _setEventCallbackPtr
      .asFunction<void Function(EventCallback)>();

  void setLogCallback(LogCallback cb) {
    return _setLogCallback(cb);
  }

  late final _setLogCallbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(LogCallback)>>(
        'setLogCallback',
      );
  late final _setLogCallback = _setLogCallbackPtr
      .asFunction<void Function(LogCallback)>();

  /// Invalidate all callbacks and wait for grace period
  void invalidateAllCallbacks() {
    return _invalidateAllCallbacks();
  }

  late final _invalidateAllCallbacksPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
        'invalidateAllCallbacks',
      );
  late final _invalidateAllCallbacks = _invalidateAllCallbacksPtr
      .asFunction<void Function()>();

  /// Caller functions - check if callback is still valid
  void callEventCallback(
    int eventType,
    ffi.Pointer<ffi.Char> roomId,
    ffi.Pointer<ffi.Char> peerId,
    ffi.Pointer<ffi.Char> data,
  ) {
    return _callEventCallback(eventType, roomId, peerId, data);
  }

  late final _callEventCallbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('callEventCallback');
  late final _callEventCallback = _callEventCallbackPtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  void callLogCallback(int level, ffi.Pointer<ffi.Char> message) {
    return _callLogCallback(level, message);
  }

  late final _callLogCallbackPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Pointer<ffi.Char>)>
      >('callLogCallback');
  late final _callLogCallback = _callLogCallbackPtr
      .asFunction<void Function(int, ffi.Pointer<ffi.Char>)>();

  /// KeepaliveCreate 创建心跳管理器
  /// intervalMs: 心跳间隔（毫秒）
  /// timeoutMs: 超时时间（毫秒）
  int KeepaliveCreate(
    ffi.Pointer<ffi.Char> roomID,
    int intervalMs,
    int timeoutMs,
  ) {
    return _KeepaliveCreate(roomID, intervalMs, timeoutMs);
  }

  late final _KeepaliveCreatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.Int)
        >
      >('KeepaliveCreate');
  late final _KeepaliveCreate =
      _KeepaliveCreatePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, int, int)
      >();

  /// KeepaliveDestroy 销毁心跳管理器
  int KeepaliveDestroy(ffi.Pointer<ffi.Char> roomID) {
    return _KeepaliveDestroy(roomID);
  }

  late final _KeepaliveDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'KeepaliveDestroy',
      );
  late final _KeepaliveDestroy =
      _KeepaliveDestroyPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// KeepaliveStart 启动心跳检测
  int KeepaliveStart(ffi.Pointer<ffi.Char> roomID) {
    return _KeepaliveStart(roomID);
  }

  late final _KeepaliveStartPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'KeepaliveStart',
      );
  late final _KeepaliveStart =
      _KeepaliveStartPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// KeepaliveStop 停止心跳检测
  int KeepaliveStop(ffi.Pointer<ffi.Char> roomID) {
    return _KeepaliveStop(roomID);
  }

  late final _KeepaliveStopPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'KeepaliveStop',
      );
  late final _KeepaliveStop =
      _KeepaliveStopPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// KeepaliveAddPeer 添加需要监控的 Peer
  int KeepaliveAddPeer(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _KeepaliveAddPeer(roomID, peerID);
  }

  late final _KeepaliveAddPeerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('KeepaliveAddPeer');
  late final _KeepaliveAddPeer =
      _KeepaliveAddPeerPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// KeepaliveRemovePeer 移除 Peer
  int KeepaliveRemovePeer(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _KeepaliveRemovePeer(roomID, peerID);
  }

  late final _KeepaliveRemovePeerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('KeepaliveRemovePeer');
  late final _KeepaliveRemovePeer =
      _KeepaliveRemovePeerPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// KeepaliveHandlePong 处理收到的 Pong
  /// 当 Dart 层收到对方的 pong 响应时调用此函数
  int KeepaliveHandlePong(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _KeepaliveHandlePong(roomID, peerID);
  }

  late final _KeepaliveHandlePongPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('KeepaliveHandlePong');
  late final _KeepaliveHandlePong =
      _KeepaliveHandlePongPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// KeepaliveGetPeerStatus 获取 Peer 状态
  /// 返回: 0=Unknown, 1=Online, 2=Slow, 3=Offline
  int KeepaliveGetPeerStatus(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _KeepaliveGetPeerStatus(roomID, peerID);
  }

  late final _KeepaliveGetPeerStatusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('KeepaliveGetPeerStatus');
  late final _KeepaliveGetPeerStatus =
      _KeepaliveGetPeerStatusPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// KeepaliveGetPeerRTT 获取 Peer 的 RTT（毫秒）
  int KeepaliveGetPeerRTT(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _KeepaliveGetPeerRTT(roomID, peerID);
  }

  late final _KeepaliveGetPeerRTTPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('KeepaliveGetPeerRTT');
  late final _KeepaliveGetPeerRTT =
      _KeepaliveGetPeerRTTPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// KeepaliveGetPeerInfo 获取 Peer 心跳详细信息
  ffi.Pointer<ffi.Char> KeepaliveGetPeerInfo(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _KeepaliveGetPeerInfo(roomID, peerID);
  }

  late final _KeepaliveGetPeerInfoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('KeepaliveGetPeerInfo');
  late final _KeepaliveGetPeerInfo =
      _KeepaliveGetPeerInfoPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// KeepaliveGetAllPeerInfo 获取所有 Peer 心跳信息
  ffi.Pointer<ffi.Char> KeepaliveGetAllPeerInfo(ffi.Pointer<ffi.Char> roomID) {
    return _KeepaliveGetAllPeerInfo(roomID);
  }

  late final _KeepaliveGetAllPeerInfoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('KeepaliveGetAllPeerInfo');
  late final _KeepaliveGetAllPeerInfo =
      _KeepaliveGetAllPeerInfoPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// SetPingCallback 设置 Ping 回调
  /// 当需要发送 ping 时会调用此回调
  void SetPingCallback(PingCallback callback) {
    return _SetPingCallback(callback);
  }

  late final _SetPingCallbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(PingCallback)>>(
        'SetPingCallback',
      );
  late final _SetPingCallback =
      _SetPingCallbackPtr.asFunction<void Function(PingCallback)>();

  /// CodecGetSupportedVideo 获取支持的视频编解码器列表
  ffi.Pointer<ffi.Char> CodecGetSupportedVideo() {
    return _CodecGetSupportedVideo();
  }

  late final _CodecGetSupportedVideoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'CodecGetSupportedVideo',
      );
  late final _CodecGetSupportedVideo =
      _CodecGetSupportedVideoPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// CodecGetSupportedAudio 获取支持的音频编解码器列表
  ffi.Pointer<ffi.Char> CodecGetSupportedAudio() {
    return _CodecGetSupportedAudio();
  }

  late final _CodecGetSupportedAudioPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'CodecGetSupportedAudio',
      );
  late final _CodecGetSupportedAudio =
      _CodecGetSupportedAudioPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// CodecParseType 解析 MimeType 获取编解码器类型
  ffi.Pointer<ffi.Char> CodecParseType(ffi.Pointer<ffi.Char> mimeType) {
    return _CodecParseType(mimeType);
  }

  late final _CodecParseTypePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('CodecParseType');
  late final _CodecParseType =
      _CodecParseTypePtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// CodecIsVideo 判断是否是视频编解码器
  int CodecIsVideo(ffi.Pointer<ffi.Char> codecType) {
    return _CodecIsVideo(codecType);
  }

  late final _CodecIsVideoPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'CodecIsVideo',
      );
  late final _CodecIsVideo =
      _CodecIsVideoPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// CodecIsAudio 判断是否是音频编解码器
  int CodecIsAudio(ffi.Pointer<ffi.Char> codecType) {
    return _CodecIsAudio(codecType);
  }

  late final _CodecIsAudioPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'CodecIsAudio',
      );
  late final _CodecIsAudio =
      _CodecIsAudioPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// LiveKitBridgeCreate 创建 LiveKit 桥接器
  /// 返回: 0 成功, -1 失败
  int LiveKitBridgeCreate(ffi.Pointer<ffi.Char> roomID) {
    return _LiveKitBridgeCreate(roomID);
  }

  late final _LiveKitBridgeCreatePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'LiveKitBridgeCreate',
      );
  late final _LiveKitBridgeCreate =
      _LiveKitBridgeCreatePtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// LiveKitBridgeConnect 连接到 LiveKit 房间
  /// 返回: 0 成功, -1 失败
  int LiveKitBridgeConnect(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> url,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _LiveKitBridgeConnect(roomID, url, token);
  }

  late final _LiveKitBridgeConnectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('LiveKitBridgeConnect');
  late final _LiveKitBridgeConnect =
      _LiveKitBridgeConnectPtr.asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// LiveKitBridgeDisconnect 断开 LiveKit 连接
  /// 返回: 0 成功, -1 失败
  int LiveKitBridgeDisconnect(ffi.Pointer<ffi.Char> roomID) {
    return _LiveKitBridgeDisconnect(roomID);
  }

  late final _LiveKitBridgeDisconnectPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'LiveKitBridgeDisconnect',
      );
  late final _LiveKitBridgeDisconnect =
      _LiveKitBridgeDisconnectPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// LiveKitBridgeDestroy 销毁 LiveKit 桥接器
  /// 返回: 0 成功
  int LiveKitBridgeDestroy(ffi.Pointer<ffi.Char> roomID) {
    return _LiveKitBridgeDestroy(roomID);
  }

  late final _LiveKitBridgeDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'LiveKitBridgeDestroy',
      );
  late final _LiveKitBridgeDestroy =
      _LiveKitBridgeDestroyPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// LiveKitBridgeGetStatus 获取桥接器状态
  /// 返回: JSON 字符串，需要调用 FreeString 释放
  ffi.Pointer<ffi.Char> LiveKitBridgeGetStatus(ffi.Pointer<ffi.Char> roomID) {
    return _LiveKitBridgeGetStatus(roomID);
  }

  late final _LiveKitBridgeGetStatusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('LiveKitBridgeGetStatus');
  late final _LiveKitBridgeGetStatus =
      _LiveKitBridgeGetStatusPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// LiveKitBridgeIsConnected 检查是否已连接
  /// 返回: 1 已连接, 0 未连接
  int LiveKitBridgeIsConnected(ffi.Pointer<ffi.Char> roomID) {
    return _LiveKitBridgeIsConnected(roomID);
  }

  late final _LiveKitBridgeIsConnectedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'LiveKitBridgeIsConnected',
      );
  late final _LiveKitBridgeIsConnected =
      _LiveKitBridgeIsConnectedPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  int ElectionEnable(int relayID, ffi.Pointer<ffi.Char> roomID) {
    return _ElectionEnable(relayID, roomID);
  }

  late final _ElectionEnablePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Int64, ffi.Pointer<ffi.Char>)>
      >('ElectionEnable');
  late final _ElectionEnable =
      _ElectionEnablePtr.asFunction<int Function(int, ffi.Pointer<ffi.Char>)>();

  int ElectionDisable(int relayID, ffi.Pointer<ffi.Char> roomID) {
    return _ElectionDisable(relayID, roomID);
  }

  late final _ElectionDisablePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Int64, ffi.Pointer<ffi.Char>)>
      >('ElectionDisable');
  late final _ElectionDisable =
      _ElectionDisablePtr.asFunction<
        int Function(int, ffi.Pointer<ffi.Char>)
      >();

  int ElectionUpdateCandidate(
    int relayID,
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
    int bandwidth,
    int latency,
    double packetLoss,
  ) {
    return _ElectionUpdateCandidate(
      relayID,
      roomID,
      peerID,
      bandwidth,
      latency,
      packetLoss,
    );
  }

  late final _ElectionUpdateCandidatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Int64,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int64,
            ffi.Int64,
            ffi.Double,
          )
        >
      >('ElectionUpdateCandidate');
  late final _ElectionUpdateCandidate =
      _ElectionUpdateCandidatePtr.asFunction<
        int Function(
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          double,
        )
      >();

  ffi.Pointer<ffi.Char> ElectionTrigger(
    int relayID,
    ffi.Pointer<ffi.Char> roomID,
  ) {
    return _ElectionTrigger(relayID, roomID);
  }

  late final _ElectionTriggerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Int64, ffi.Pointer<ffi.Char>)
        >
      >('ElectionTrigger');
  late final _ElectionTrigger =
      _ElectionTriggerPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)
      >();

  ffi.Pointer<ffi.Char> ElectionGetProxy(
    int relayID,
    ffi.Pointer<ffi.Char> roomID,
  ) {
    return _ElectionGetProxy(relayID, roomID);
  }

  late final _ElectionGetProxyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Int64, ffi.Pointer<ffi.Char>)
        >
      >('ElectionGetProxy');
  late final _ElectionGetProxy =
      _ElectionGetProxyPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)
      >();

  void SetEventCallback(EventCallback callback) {
    return _SetEventCallback(callback);
  }

  late final _SetEventCallbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(EventCallback)>>(
        'SetEventCallback',
      );
  late final _SetEventCallback =
      _SetEventCallbackPtr.asFunction<void Function(EventCallback)>();

  void SetLogCallback(LogCallback callback) {
    return _SetLogCallback(callback);
  }

  late final _SetLogCallbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(LogCallback)>>(
        'SetLogCallback',
      );
  late final _SetLogCallback =
      _SetLogCallbackPtr.asFunction<void Function(LogCallback)>();

  void SetLogLevel(int level) {
    return _SetLogLevel(level);
  }

  late final _SetLogLevelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>('SetLogLevel');
  late final _SetLogLevel = _SetLogLevelPtr.asFunction<void Function(int)>();

  void FreeString(ffi.Pointer<ffi.Char> s) {
    return _FreeString(s);
  }

  late final _FreeStringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'FreeString',
      );
  late final _FreeString =
      _FreeStringPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void CleanupAll() {
    return _CleanupAll();
  }

  late final _CleanupAllPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'CleanupAll',
  );
  late final _CleanupAll = _CleanupAllPtr.asFunction<void Function()>();

  ffi.Pointer<ffi.Char> GetVersion() {
    return _GetVersion();
  }

  late final _GetVersionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'GetVersion',
      );
  late final _GetVersion =
      _GetVersionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// SourceSwitcherCreate 创建源切换器
  int SourceSwitcherCreate(ffi.Pointer<ffi.Char> roomID) {
    return _SourceSwitcherCreate(roomID);
  }

  late final _SourceSwitcherCreatePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'SourceSwitcherCreate',
      );
  late final _SourceSwitcherCreate =
      _SourceSwitcherCreatePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// SourceSwitcherDestroy 销毁源切换器
  int SourceSwitcherDestroy(ffi.Pointer<ffi.Char> roomID) {
    return _SourceSwitcherDestroy(roomID);
  }

  late final _SourceSwitcherDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'SourceSwitcherDestroy',
      );
  late final _SourceSwitcherDestroy =
      _SourceSwitcherDestroyPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// SourceSwitcherInjectSFU 注入来自 SFU 的 RTP 包
  /// isVideo: 1 = video, 0 = audio
  /// data: RTP 原始数据
  /// dataLen: 数据长度
  int SourceSwitcherInjectSFU(
    ffi.Pointer<ffi.Char> roomID,
    int isVideo,
    ffi.Pointer<ffi.Void> data,
    int dataLen,
  ) {
    return _SourceSwitcherInjectSFU(roomID, isVideo, data, dataLen);
  }

  late final _SourceSwitcherInjectSFUPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
          )
        >
      >('SourceSwitcherInjectSFU');
  late final _SourceSwitcherInjectSFU =
      _SourceSwitcherInjectSFUPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Void>, int)
      >();

  /// SourceSwitcherInjectLocal 注入来自本地分享者的 RTP 包
  int SourceSwitcherInjectLocal(
    ffi.Pointer<ffi.Char> roomID,
    int isVideo,
    ffi.Pointer<ffi.Void> data,
    int dataLen,
  ) {
    return _SourceSwitcherInjectLocal(roomID, isVideo, data, dataLen);
  }

  late final _SourceSwitcherInjectLocalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
          )
        >
      >('SourceSwitcherInjectLocal');
  late final _SourceSwitcherInjectLocal =
      _SourceSwitcherInjectLocalPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Void>, int)
      >();

  /// SourceSwitcherStartLocalShare 开始本地分享
  int SourceSwitcherStartLocalShare(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> sharerID,
  ) {
    return _SourceSwitcherStartLocalShare(roomID, sharerID);
  }

  late final _SourceSwitcherStartLocalSharePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('SourceSwitcherStartLocalShare');
  late final _SourceSwitcherStartLocalShare =
      _SourceSwitcherStartLocalSharePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// SourceSwitcherStopLocalShare 停止本地分享
  int SourceSwitcherStopLocalShare(ffi.Pointer<ffi.Char> roomID) {
    return _SourceSwitcherStopLocalShare(roomID);
  }

  late final _SourceSwitcherStopLocalSharePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'SourceSwitcherStopLocalShare',
      );
  late final _SourceSwitcherStopLocalShare =
      _SourceSwitcherStopLocalSharePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// SourceSwitcherGetStatus 获取源切换器状态
  ffi.Pointer<ffi.Char> SourceSwitcherGetStatus(ffi.Pointer<ffi.Char> roomID) {
    return _SourceSwitcherGetStatus(roomID);
  }

  late final _SourceSwitcherGetStatusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('SourceSwitcherGetStatus');
  late final _SourceSwitcherGetStatus =
      _SourceSwitcherGetStatusPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// SourceSwitcherIsLocalSharing 检查是否正在本地分享
  int SourceSwitcherIsLocalSharing(ffi.Pointer<ffi.Char> roomID) {
    return _SourceSwitcherIsLocalSharing(roomID);
  }

  late final _SourceSwitcherIsLocalSharingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'SourceSwitcherIsLocalSharing',
      );
  late final _SourceSwitcherIsLocalSharing =
      _SourceSwitcherIsLocalSharingPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// ElectionUpdateDeviceInfo 更新设备信息
  /// deviceType: 0=Unknown, 1=PC, 2=Pad, 3=Mobile, 4=TV
  /// connectionType: 0=Unknown, 1=Ethernet, 2=WiFi, 3=Cellular
  /// powerState: 0=Unknown, 1=PluggedIn, 2=Battery, 3=LowBattery
  int ElectionUpdateDeviceInfo(
    int relayID,
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
    int deviceType,
    int connectionType,
    int powerState,
  ) {
    return _ElectionUpdateDeviceInfo(
      relayID,
      roomID,
      peerID,
      deviceType,
      connectionType,
      powerState,
    );
  }

  late final _ElectionUpdateDeviceInfoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Int64,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('ElectionUpdateDeviceInfo');
  late final _ElectionUpdateDeviceInfo =
      _ElectionUpdateDeviceInfoPtr.asFunction<
        int Function(
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          int,
        )
      >();

  /// ElectionUpdateNetworkMetrics 更新网络指标
  int ElectionUpdateNetworkMetrics(
    int relayID,
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
    int bandwidth,
    int latency,
    double packetLoss,
  ) {
    return _ElectionUpdateNetworkMetrics(
      relayID,
      roomID,
      peerID,
      bandwidth,
      latency,
      packetLoss,
    );
  }

  late final _ElectionUpdateNetworkMetricsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Int64,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int64,
            ffi.Int64,
            ffi.Double,
          )
        >
      >('ElectionUpdateNetworkMetrics');
  late final _ElectionUpdateNetworkMetrics =
      _ElectionUpdateNetworkMetricsPtr.asFunction<
        int Function(
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          double,
        )
      >();

  /// ElectionGetCandidates 获取所有候选者列表
  ffi.Pointer<ffi.Char> ElectionGetCandidates(
    int relayID,
    ffi.Pointer<ffi.Char> roomID,
  ) {
    return _ElectionGetCandidates(relayID, roomID);
  }

  late final _ElectionGetCandidatesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Int64, ffi.Pointer<ffi.Char>)
        >
      >('ElectionGetCandidates');
  late final _ElectionGetCandidates =
      _ElectionGetCandidatesPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)
      >();

  /// ProxyModeInit 初始化代理模式（创建 SourceSwitcher + 启用选举）
  int ProxyModeInit(int relayID, ffi.Pointer<ffi.Char> roomID) {
    return _ProxyModeInit(relayID, roomID);
  }

  late final _ProxyModeInitPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Int64, ffi.Pointer<ffi.Char>)>
      >('ProxyModeInit');
  late final _ProxyModeInit =
      _ProxyModeInitPtr.asFunction<int Function(int, ffi.Pointer<ffi.Char>)>();

  /// ProxyModeCleanup 清理代理模式
  int ProxyModeCleanup(int relayID, ffi.Pointer<ffi.Char> roomID) {
    return _ProxyModeCleanup(relayID, roomID);
  }

  late final _ProxyModeCleanupPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Int64, ffi.Pointer<ffi.Char>)>
      >('ProxyModeCleanup');
  late final _ProxyModeCleanup =
      _ProxyModeCleanupPtr.asFunction<
        int Function(int, ffi.Pointer<ffi.Char>)
      >();

  /// ProxyModeGetStatus 获取代理模式综合状态
  ffi.Pointer<ffi.Char> ProxyModeGetStatus(
    int relayID,
    ffi.Pointer<ffi.Char> roomID,
  ) {
    return _ProxyModeGetStatus(relayID, roomID);
  }

  late final _ProxyModeGetStatusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Int64, ffi.Pointer<ffi.Char>)
        >
      >('ProxyModeGetStatus');
  late final _ProxyModeGetStatus =
      _ProxyModeGetStatusPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>)
      >();

  /// FailoverEnable 启用自动故障切换
  /// localPeerID: 本机 Peer ID
  int FailoverEnable(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> localPeerID,
  ) {
    return _FailoverEnable(roomID, localPeerID);
  }

  late final _FailoverEnablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('FailoverEnable');
  late final _FailoverEnable =
      _FailoverEnablePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// FailoverDisable 禁用自动故障切换
  int FailoverDisable(ffi.Pointer<ffi.Char> roomID) {
    return _FailoverDisable(roomID);
  }

  late final _FailoverDisablePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'FailoverDisable',
      );
  late final _FailoverDisable =
      _FailoverDisablePtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// FailoverSetCurrentRelay 设置当前 Relay
  int FailoverSetCurrentRelay(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> relayID,
    int epoch,
  ) {
    return _FailoverSetCurrentRelay(roomID, relayID, epoch);
  }

  late final _FailoverSetCurrentRelayPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Uint64,
          )
        >
      >('FailoverSetCurrentRelay');
  late final _FailoverSetCurrentRelay =
      _FailoverSetCurrentRelayPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  /// FailoverUpdateLocalScore 更新本机分数
  int FailoverUpdateLocalScore(ffi.Pointer<ffi.Char> roomID, double score) {
    return _FailoverUpdateLocalScore(roomID, score);
  }

  late final _FailoverUpdateLocalScorePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Double)>
      >('FailoverUpdateLocalScore');
  late final _FailoverUpdateLocalScore =
      _FailoverUpdateLocalScorePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, double)
      >();

  /// FailoverReceiveClaim 接收其他节点的 Relay 声明
  /// epoch: 选举纪元号
  /// score: 声明者的分数（用于同 epoch 冲突解决）
  int FailoverReceiveClaim(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
    int epoch,
    double score,
  ) {
    return _FailoverReceiveClaim(roomID, peerID, epoch, score);
  }

  late final _FailoverReceiveClaimPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Uint64,
            ffi.Double,
          )
        >
      >('FailoverReceiveClaim');
  late final _FailoverReceiveClaim =
      _FailoverReceiveClaimPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, double)
      >();

  /// FailoverGetState 获取故障切换状态
  ffi.Pointer<ffi.Char> FailoverGetState(ffi.Pointer<ffi.Char> roomID) {
    return _FailoverGetState(roomID);
  }

  late final _FailoverGetStatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('FailoverGetState');
  late final _FailoverGetState =
      _FailoverGetStatePtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// CoordinatorEnable 一键启用自动代理模式
  /// 自动管理：心跳、选举、故障切换、Relay 接管
  /// 用户无需关心内部细节，完全自动
  int CoordinatorEnable(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> localPeerID,
  ) {
    return _CoordinatorEnable(roomID, localPeerID);
  }

  late final _CoordinatorEnablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('CoordinatorEnable');
  late final _CoordinatorEnable =
      _CoordinatorEnablePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// CoordinatorDisable 禁用自动代理模式
  int CoordinatorDisable(ffi.Pointer<ffi.Char> roomID) {
    return _CoordinatorDisable(roomID);
  }

  late final _CoordinatorDisablePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'CoordinatorDisable',
      );
  late final _CoordinatorDisable =
      _CoordinatorDisablePtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// CoordinatorAddPeer 添加 Peer 到自动管理
  int CoordinatorAddPeer(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
    int deviceType,
    int connectionType,
    int powerState,
  ) {
    return _CoordinatorAddPeer(
      roomID,
      peerID,
      deviceType,
      connectionType,
      powerState,
    );
  }

  late final _CoordinatorAddPeerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('CoordinatorAddPeer');
  late final _CoordinatorAddPeer =
      _CoordinatorAddPeerPtr.asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          int,
        )
      >();

  /// CoordinatorRemovePeer 移除 Peer
  int CoordinatorRemovePeer(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _CoordinatorRemovePeer(roomID, peerID);
  }

  late final _CoordinatorRemovePeerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('CoordinatorRemovePeer');
  late final _CoordinatorRemovePeer =
      _CoordinatorRemovePeerPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// CoordinatorHandlePong 处理 Pong（心跳响应）
  int CoordinatorHandlePong(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _CoordinatorHandlePong(roomID, peerID);
  }

  late final _CoordinatorHandlePongPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('CoordinatorHandlePong');
  late final _CoordinatorHandlePong =
      _CoordinatorHandlePongPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// CoordinatorSetRelay 设置当前 Relay（收到外部通知时）
  int CoordinatorSetRelay(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> relayID,
    int epoch,
  ) {
    return _CoordinatorSetRelay(roomID, relayID, epoch);
  }

  late final _CoordinatorSetRelayPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Uint64,
          )
        >
      >('CoordinatorSetRelay');
  late final _CoordinatorSetRelay =
      _CoordinatorSetRelayPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  /// CoordinatorReceiveClaim 接收 Relay 声明
  /// epoch: 选举纪元号
  /// score: 声明者分数（用于同 epoch 冲突解决）
  int CoordinatorReceiveClaim(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
    int epoch,
    double score,
  ) {
    return _CoordinatorReceiveClaim(roomID, peerID, epoch, score);
  }

  late final _CoordinatorReceiveClaimPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Uint64,
            ffi.Double,
          )
        >
      >('CoordinatorReceiveClaim');
  late final _CoordinatorReceiveClaim =
      _CoordinatorReceiveClaimPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int, double)
      >();

  /// CoordinatorUpdateLocalDevice 更新本机设备信息
  int CoordinatorUpdateLocalDevice(
    ffi.Pointer<ffi.Char> roomID,
    int deviceType,
    int connectionType,
    int powerState,
  ) {
    return _CoordinatorUpdateLocalDevice(
      roomID,
      deviceType,
      connectionType,
      powerState,
    );
  }

  late final _CoordinatorUpdateLocalDevicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.Int, ffi.Int)
        >
      >('CoordinatorUpdateLocalDevice');
  late final _CoordinatorUpdateLocalDevice =
      _CoordinatorUpdateLocalDevicePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, int, int, int)
      >();

  /// CoordinatorInjectSFU 注入 SFU RTP 包
  int CoordinatorInjectSFU(
    ffi.Pointer<ffi.Char> roomID,
    int isVideo,
    ffi.Pointer<ffi.Void> data,
    int dataLen,
  ) {
    return _CoordinatorInjectSFU(roomID, isVideo, data, dataLen);
  }

  late final _CoordinatorInjectSFUPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
          )
        >
      >('CoordinatorInjectSFU');
  late final _CoordinatorInjectSFU =
      _CoordinatorInjectSFUPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Void>, int)
      >();

  /// CoordinatorInjectLocal 注入本地分享 RTP 包
  int CoordinatorInjectLocal(
    ffi.Pointer<ffi.Char> roomID,
    int isVideo,
    ffi.Pointer<ffi.Void> data,
    int dataLen,
  ) {
    return _CoordinatorInjectLocal(roomID, isVideo, data, dataLen);
  }

  late final _CoordinatorInjectLocalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
          )
        >
      >('CoordinatorInjectLocal');
  late final _CoordinatorInjectLocal =
      _CoordinatorInjectLocalPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Void>, int)
      >();

  /// CoordinatorStartLocalShare 开始本地分享
  int CoordinatorStartLocalShare(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> sharerID,
  ) {
    return _CoordinatorStartLocalShare(roomID, sharerID);
  }

  late final _CoordinatorStartLocalSharePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('CoordinatorStartLocalShare');
  late final _CoordinatorStartLocalShare =
      _CoordinatorStartLocalSharePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// CoordinatorStopLocalShare 停止本地分享
  int CoordinatorStopLocalShare(ffi.Pointer<ffi.Char> roomID) {
    return _CoordinatorStopLocalShare(roomID);
  }

  late final _CoordinatorStopLocalSharePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'CoordinatorStopLocalShare',
      );
  late final _CoordinatorStopLocalShare =
      _CoordinatorStopLocalSharePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// CoordinatorGetStatus 获取协调器状态
  ffi.Pointer<ffi.Char> CoordinatorGetStatus(ffi.Pointer<ffi.Char> roomID) {
    return _CoordinatorGetStatus(roomID);
  }

  late final _CoordinatorGetStatusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('CoordinatorGetStatus');
  late final _CoordinatorGetStatus =
      _CoordinatorGetStatusPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// CoordinatorIsRelay 检查本机是否是 Relay
  int CoordinatorIsRelay(ffi.Pointer<ffi.Char> roomID) {
    return _CoordinatorIsRelay(roomID);
  }

  late final _CoordinatorIsRelayPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'CoordinatorIsRelay',
      );
  late final _CoordinatorIsRelay =
      _CoordinatorIsRelayPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// RelayRoomCreate 创建代理房间
  /// iceServersJSON: ICE 服务器配置 JSON
  int RelayRoomCreate(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> iceServersJSON,
  ) {
    return _RelayRoomCreate(roomID, iceServersJSON);
  }

  late final _RelayRoomCreatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('RelayRoomCreate');
  late final _RelayRoomCreate =
      _RelayRoomCreatePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// RelayRoomDestroy 销毁代理房间
  int RelayRoomDestroy(ffi.Pointer<ffi.Char> roomID) {
    return _RelayRoomDestroy(roomID);
  }

  late final _RelayRoomDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'RelayRoomDestroy',
      );
  late final _RelayRoomDestroy =
      _RelayRoomDestroyPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// RelayRoomBecomeRelay 成为 Relay 节点
  int RelayRoomBecomeRelay(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _RelayRoomBecomeRelay(roomID, peerID);
  }

  late final _RelayRoomBecomeRelayPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('RelayRoomBecomeRelay');
  late final _RelayRoomBecomeRelay =
      _RelayRoomBecomeRelayPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// RelayRoomIsRelay 检查是否是 Relay 节点
  int RelayRoomIsRelay(ffi.Pointer<ffi.Char> roomID) {
    return _RelayRoomIsRelay(roomID);
  }

  late final _RelayRoomIsRelayPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'RelayRoomIsRelay',
      );
  late final _RelayRoomIsRelay =
      _RelayRoomIsRelayPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// RelayRoomAddSubscriber 添加订阅者
  /// 使用远端 Offer 创建 P2P 连接，返回 Answer SDP
  ffi.Pointer<ffi.Char> RelayRoomAddSubscriber(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
    ffi.Pointer<ffi.Char> offerSDP,
  ) {
    return _RelayRoomAddSubscriber(roomID, peerID, offerSDP);
  }

  late final _RelayRoomAddSubscriberPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('RelayRoomAddSubscriber');
  late final _RelayRoomAddSubscriber =
      _RelayRoomAddSubscriberPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// RelayRoomRemoveSubscriber 移除订阅者
  int RelayRoomRemoveSubscriber(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _RelayRoomRemoveSubscriber(roomID, peerID);
  }

  late final _RelayRoomRemoveSubscriberPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('RelayRoomRemoveSubscriber');
  late final _RelayRoomRemoveSubscriber =
      _RelayRoomRemoveSubscriberPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// RelayRoomGetSubscribers 获取订阅者列表
  ffi.Pointer<ffi.Char> RelayRoomGetSubscribers(ffi.Pointer<ffi.Char> roomID) {
    return _RelayRoomGetSubscribers(roomID);
  }

  late final _RelayRoomGetSubscribersPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('RelayRoomGetSubscribers');
  late final _RelayRoomGetSubscribers =
      _RelayRoomGetSubscribersPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// RelayRoomGetSubscriberCount 获取订阅者数量
  int RelayRoomGetSubscriberCount(ffi.Pointer<ffi.Char> roomID) {
    return _RelayRoomGetSubscriberCount(roomID);
  }

  late final _RelayRoomGetSubscriberCountPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'RelayRoomGetSubscriberCount',
      );
  late final _RelayRoomGetSubscriberCount =
      _RelayRoomGetSubscriberCountPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// RelayRoomAddICECandidate 添加 ICE 候选
  int RelayRoomAddICECandidate(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
    ffi.Pointer<ffi.Char> candidateJSON,
  ) {
    return _RelayRoomAddICECandidate(roomID, peerID, candidateJSON);
  }

  late final _RelayRoomAddICECandidatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('RelayRoomAddICECandidate');
  late final _RelayRoomAddICECandidate =
      _RelayRoomAddICECandidatePtr.asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// RelayRoomTriggerRenegotiation 触发重协商
  /// 为所有已连接的订阅者生成新的 Offer
  /// 返回 JSON: {"peerID1": "offer1", "peerID2": "offer2", ...}
  ffi.Pointer<ffi.Char> RelayRoomTriggerRenegotiation(
    ffi.Pointer<ffi.Char> roomID,
  ) {
    return _RelayRoomTriggerRenegotiation(roomID);
  }

  late final _RelayRoomTriggerRenegotiationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('RelayRoomTriggerRenegotiation');
  late final _RelayRoomTriggerRenegotiation =
      _RelayRoomTriggerRenegotiationPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// RelayRoomCreateOffer 为指定订阅者创建 Offer
  ffi.Pointer<ffi.Char> RelayRoomCreateOffer(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _RelayRoomCreateOffer(roomID, peerID);
  }

  late final _RelayRoomCreateOfferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('RelayRoomCreateOffer');
  late final _RelayRoomCreateOffer =
      _RelayRoomCreateOfferPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// RelayRoomHandleAnswer 处理订阅者的 Answer（重协商响应）
  int RelayRoomHandleAnswer(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
    ffi.Pointer<ffi.Char> answerSDP,
  ) {
    return _RelayRoomHandleAnswer(roomID, peerID, answerSDP);
  }

  late final _RelayRoomHandleAnswerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('RelayRoomHandleAnswer');
  late final _RelayRoomHandleAnswer =
      _RelayRoomHandleAnswerPtr.asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// RelayRoomGetStatus 获取房间状态
  ffi.Pointer<ffi.Char> RelayRoomGetStatus(ffi.Pointer<ffi.Char> roomID) {
    return _RelayRoomGetStatus(roomID);
  }

  late final _RelayRoomGetStatusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('RelayRoomGetStatus');
  late final _RelayRoomGetStatus =
      _RelayRoomGetStatusPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// RelayRoomInjectSFU 注入 SFU RTP 包（通过 RelayRoom）
  int RelayRoomInjectSFU(
    ffi.Pointer<ffi.Char> roomID,
    int isVideo,
    ffi.Pointer<ffi.Void> data,
    int dataLen,
  ) {
    return _RelayRoomInjectSFU(roomID, isVideo, data, dataLen);
  }

  late final _RelayRoomInjectSFUPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
          )
        >
      >('RelayRoomInjectSFU');
  late final _RelayRoomInjectSFU =
      _RelayRoomInjectSFUPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Void>, int)
      >();

  /// RelayRoomInjectLocal 注入本地分享 RTP 包（通过 RelayRoom）
  int RelayRoomInjectLocal(
    ffi.Pointer<ffi.Char> roomID,
    int isVideo,
    ffi.Pointer<ffi.Void> data,
    int dataLen,
  ) {
    return _RelayRoomInjectLocal(roomID, isVideo, data, dataLen);
  }

  late final _RelayRoomInjectLocalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Void>,
            ffi.Int,
          )
        >
      >('RelayRoomInjectLocal');
  late final _RelayRoomInjectLocal =
      _RelayRoomInjectLocalPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Void>, int)
      >();

  /// RelayRoomStartLocalShare 开始本地分享
  int RelayRoomStartLocalShare(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> sharerID,
  ) {
    return _RelayRoomStartLocalShare(roomID, sharerID);
  }

  late final _RelayRoomStartLocalSharePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('RelayRoomStartLocalShare');
  late final _RelayRoomStartLocalShare =
      _RelayRoomStartLocalSharePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// RelayRoomStopLocalShare 停止本地分享
  int RelayRoomStopLocalShare(ffi.Pointer<ffi.Char> roomID) {
    return _RelayRoomStopLocalShare(roomID);
  }

  late final _RelayRoomStopLocalSharePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'RelayRoomStopLocalShare',
      );
  late final _RelayRoomStopLocalShare =
      _RelayRoomStopLocalSharePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// RelayRoomHandleLocalPublisherOffer 处理本地 Loopback P2P 连接 Offer
  ffi.Pointer<ffi.Char> RelayRoomHandleLocalPublisherOffer(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> offerSDP,
  ) {
    return _RelayRoomHandleLocalPublisherOffer(roomID, offerSDP);
  }

  late final _RelayRoomHandleLocalPublisherOfferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('RelayRoomHandleLocalPublisherOffer');
  late final _RelayRoomHandleLocalPublisherOffer =
      _RelayRoomHandleLocalPublisherOfferPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// BufferPoolGetStats 获取全局缓冲池统计
  ffi.Pointer<ffi.Char> BufferPoolGetStats() {
    return _BufferPoolGetStats();
  }

  late final _BufferPoolGetStatsPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'BufferPoolGetStats',
      );
  late final _BufferPoolGetStats =
      _BufferPoolGetStatsPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// BufferPoolResetStats 重置缓冲池统计
  void BufferPoolResetStats() {
    return _BufferPoolResetStats();
  }

  late final _BufferPoolResetStatsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('BufferPoolResetStats');
  late final _BufferPoolResetStats =
      _BufferPoolResetStatsPtr.asFunction<void Function()>();

  /// StatsCreate 创建房间统计
  int StatsCreate(ffi.Pointer<ffi.Char> roomID) {
    return _StatsCreate(roomID);
  }

  late final _StatsCreatePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'StatsCreate',
      );
  late final _StatsCreate =
      _StatsCreatePtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// StatsDestroy 销毁房间统计
  int StatsDestroy(ffi.Pointer<ffi.Char> roomID) {
    return _StatsDestroy(roomID);
  }

  late final _StatsDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'StatsDestroy',
      );
  late final _StatsDestroy =
      _StatsDestroyPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// StatsAddBytesIn 添加接收字节数
  int StatsAddBytesIn(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
    int bytes,
  ) {
    return _StatsAddBytesIn(roomID, peerID, bytes);
  }

  late final _StatsAddBytesInPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Uint64,
          )
        >
      >('StatsAddBytesIn');
  late final _StatsAddBytesIn =
      _StatsAddBytesInPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  /// StatsAddBytesOut 添加发送字节数
  int StatsAddBytesOut(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
    int bytes,
  ) {
    return _StatsAddBytesOut(roomID, peerID, bytes);
  }

  late final _StatsAddBytesOutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Uint64,
          )
        >
      >('StatsAddBytesOut');
  late final _StatsAddBytesOut =
      _StatsAddBytesOutPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  /// StatsAddPacketLost 添加丢包数
  int StatsAddPacketLost(ffi.Pointer<ffi.Char> roomID) {
    return _StatsAddPacketLost(roomID);
  }

  late final _StatsAddPacketLostPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'StatsAddPacketLost',
      );
  late final _StatsAddPacketLost =
      _StatsAddPacketLostPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// StatsCalculateBitrate 计算码率（每秒调用一次）
  int StatsCalculateBitrate(ffi.Pointer<ffi.Char> roomID) {
    return _StatsCalculateBitrate(roomID);
  }

  late final _StatsCalculateBitratePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'StatsCalculateBitrate',
      );
  late final _StatsCalculateBitrate =
      _StatsCalculateBitratePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();

  /// StatsGetSnapshot 获取统计快照
  ffi.Pointer<ffi.Char> StatsGetSnapshot(ffi.Pointer<ffi.Char> roomID) {
    return _StatsGetSnapshot(roomID);
  }

  late final _StatsGetSnapshotPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('StatsGetSnapshot');
  late final _StatsGetSnapshot =
      _StatsGetSnapshotPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// StatsGetTraffic 获取总体流量统计
  ffi.Pointer<ffi.Char> StatsGetTraffic(ffi.Pointer<ffi.Char> roomID) {
    return _StatsGetTraffic(roomID);
  }

  late final _StatsGetTrafficPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('StatsGetTraffic');
  late final _StatsGetTraffic =
      _StatsGetTrafficPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// StatsGetBitrateIn 获取入站码率 (bps)
  double StatsGetBitrateIn(ffi.Pointer<ffi.Char> roomID) {
    return _StatsGetBitrateIn(roomID);
  }

  late final _StatsGetBitrateInPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<ffi.Char>)>>(
        'StatsGetBitrateIn',
      );
  late final _StatsGetBitrateIn =
      _StatsGetBitrateInPtr.asFunction<
        double Function(ffi.Pointer<ffi.Char>)
      >();

  /// StatsGetBitrateOut 获取出站码率 (bps)
  double StatsGetBitrateOut(ffi.Pointer<ffi.Char> roomID) {
    return _StatsGetBitrateOut(roomID);
  }

  late final _StatsGetBitrateOutPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<ffi.Char>)>>(
        'StatsGetBitrateOut',
      );
  late final _StatsGetBitrateOut =
      _StatsGetBitrateOutPtr.asFunction<
        double Function(ffi.Pointer<ffi.Char>)
      >();

  /// StatsGetLossRate 获取丢包率
  double StatsGetLossRate(ffi.Pointer<ffi.Char> roomID) {
    return _StatsGetLossRate(roomID);
  }

  late final _StatsGetLossRatePtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<ffi.Char>)>>(
        'StatsGetLossRate',
      );
  late final _StatsGetLossRate =
      _StatsGetLossRatePtr.asFunction<double Function(ffi.Pointer<ffi.Char>)>();

  /// NetworkProbeCreate 创建网络探测管理器
  int NetworkProbeCreate(ffi.Pointer<ffi.Char> roomID) {
    return _NetworkProbeCreate(roomID);
  }

  late final _NetworkProbeCreatePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'NetworkProbeCreate',
      );
  late final _NetworkProbeCreate =
      _NetworkProbeCreatePtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// NetworkProbeDestroy 销毁网络探测管理器
  int NetworkProbeDestroy(ffi.Pointer<ffi.Char> roomID) {
    return _NetworkProbeDestroy(roomID);
  }

  late final _NetworkProbeDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'NetworkProbeDestroy',
      );
  late final _NetworkProbeDestroy =
      _NetworkProbeDestroyPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// NetworkProbeGetMetrics 获取指定 Peer 的网络指标
  ffi.Pointer<ffi.Char> NetworkProbeGetMetrics(
    ffi.Pointer<ffi.Char> roomID,
    ffi.Pointer<ffi.Char> peerID,
  ) {
    return _NetworkProbeGetMetrics(roomID, peerID);
  }

  late final _NetworkProbeGetMetricsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('NetworkProbeGetMetrics');
  late final _NetworkProbeGetMetrics =
      _NetworkProbeGetMetricsPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// NetworkProbeGetAllMetrics 获取所有 Peer 的网络指标
  ffi.Pointer<ffi.Char> NetworkProbeGetAllMetrics(
    ffi.Pointer<ffi.Char> roomID,
  ) {
    return _NetworkProbeGetAllMetrics(roomID);
  }

  late final _NetworkProbeGetAllMetricsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('NetworkProbeGetAllMetrics');
  late final _NetworkProbeGetAllMetrics =
      _NetworkProbeGetAllMetricsPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// JitterBufferCreate 创建抖动缓冲
  /// enabled: 是否启用
  /// targetDelayMs: 目标延迟（毫秒）
  int JitterBufferCreate(
    ffi.Pointer<ffi.Char> key,
    int enabled,
    int targetDelayMs,
  ) {
    return _JitterBufferCreate(key, enabled, targetDelayMs);
  }

  late final _JitterBufferCreatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.Int)
        >
      >('JitterBufferCreate');
  late final _JitterBufferCreate =
      _JitterBufferCreatePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, int, int)
      >();

  /// JitterBufferDestroy 销毁抖动缓冲
  int JitterBufferDestroy(ffi.Pointer<ffi.Char> key) {
    return _JitterBufferDestroy(key);
  }

  late final _JitterBufferDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'JitterBufferDestroy',
      );
  late final _JitterBufferDestroy =
      _JitterBufferDestroyPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// JitterBufferEnable 启用/禁用抖动缓冲
  int JitterBufferEnable(ffi.Pointer<ffi.Char> key, int enabled) {
    return _JitterBufferEnable(key, enabled);
  }

  late final _JitterBufferEnablePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int)>
      >('JitterBufferEnable');
  late final _JitterBufferEnable =
      _JitterBufferEnablePtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, int)
      >();

  /// JitterBufferSetDelay 设置目标延迟
  int JitterBufferSetDelay(ffi.Pointer<ffi.Char> key, int delayMs) {
    return _JitterBufferSetDelay(key, delayMs);
  }

  late final _JitterBufferSetDelayPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int)>
      >('JitterBufferSetDelay');
  late final _JitterBufferSetDelay =
      _JitterBufferSetDelayPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, int)
      >();

  /// JitterBufferFlush 清空缓冲区
  int JitterBufferFlush(ffi.Pointer<ffi.Char> key) {
    return _JitterBufferFlush(key);
  }

  late final _JitterBufferFlushPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'JitterBufferFlush',
      );
  late final _JitterBufferFlush =
      _JitterBufferFlushPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// JitterBufferGetStats 获取抖动缓冲统计
  ffi.Pointer<ffi.Char> JitterBufferGetStats(ffi.Pointer<ffi.Char> key) {
    return _JitterBufferGetStats(key);
  }

  late final _JitterBufferGetStatsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('JitterBufferGetStats');
  late final _JitterBufferGetStats =
      _JitterBufferGetStatsPtr.asFunction<
        ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
      >();

  /// JitterBufferIsEnabled 检查是否启用
  int JitterBufferIsEnabled(ffi.Pointer<ffi.Char> key) {
    return _JitterBufferIsEnabled(key);
  }

  late final _JitterBufferIsEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'JitterBufferIsEnabled',
      );
  late final _JitterBufferIsEnabled =
      _JitterBufferIsEnabledPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>)
      >();
}

final class _GoString_ extends ffi.Struct {
  external ffi.Pointer<ffi.Char> p;

  @ptrdiff_t()
  external int n;
}

typedef ptrdiff_t = __darwin_ptrdiff_t;
typedef __darwin_ptrdiff_t = ffi.Long;
typedef Dart__darwin_ptrdiff_t = int;
typedef pthread_mutex_t = __darwin_pthread_mutex_t;
typedef __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;

final class _opaque_pthread_mutex_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

/// Ping 回调函数类型
typedef PingCallback = ffi.Pointer<ffi.NativeFunction<PingCallbackFunction>>;
typedef PingCallbackFunction = ffi.Void Function(ffi.Pointer<ffi.Char> peerID);
typedef DartPingCallbackFunction = void Function(ffi.Pointer<ffi.Char> peerID);

/// Callback function types for events
typedef EventCallback = ffi.Pointer<ffi.NativeFunction<EventCallbackFunction>>;
typedef EventCallbackFunction =
    ffi.Void Function(
      ffi.Int eventType,
      ffi.Pointer<ffi.Char> roomId,
      ffi.Pointer<ffi.Char> peerId,
      ffi.Pointer<ffi.Char> data,
    );
typedef DartEventCallbackFunction =
    void Function(
      int eventType,
      ffi.Pointer<ffi.Char> roomId,
      ffi.Pointer<ffi.Char> peerId,
      ffi.Pointer<ffi.Char> data,
    );
typedef LogCallback = ffi.Pointer<ffi.NativeFunction<LogCallbackFunction>>;
typedef LogCallbackFunction =
    ffi.Void Function(ffi.Int level, ffi.Pointer<ffi.Char> message);
typedef DartLogCallbackFunction =
    void Function(int level, ffi.Pointer<ffi.Char> message);

final class GoInterface extends ffi.Struct {
  external ffi.Pointer<ffi.Void> t;

  external ffi.Pointer<ffi.Void> v;
}

final class GoSlice extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  @GoInt()
  external int len;

  @GoInt()
  external int cap;
}

typedef GoInt = GoInt64;
typedef GoInt64 = ffi.LongLong;
typedef DartGoInt64 = int;
